// Generated by CoffeeScript 1.6.2
var Person, adapter, ajaxHash, ajaxType, ajaxUrl, expect, expectData, expectState, expectStates, expectType, expectUrl, people, person, store;

adapter = void 0;

store = void 0;

ajaxUrl = void 0;

ajaxType = void 0;

ajaxHash = void 0;

Person = void 0;

person = void 0;

people = void 0;

expect = function(a, b) {
  return assert.equal(a, b);
};

expectUrl = function(url) {
  return expect(ajaxUrl, url);
};

expectType = function(type) {
  return expect(ajaxType, type);
};

expectData = function(hash) {
  return assert.deepEqual(ajaxHash.data, hash);
};

expectState = function(state, value, p) {
  var flag, hasState;

  p = p || person;
  if (value === undefined) {
    value = true;
  }
  flag = 'is' + state.charAt(0).toUpperCase() + state.substr(1);
  hasState = get(p, flag);
  if (value === true) {
    return expect(hasState, true);
  } else {
    return expect(hasState, false);
  }
};

expectStates = function(state, value) {
  return people.forEach(function(person) {
    return expect(state, value, person);
  });
};

describe('Adapter', function() {
  beforeEach(function() {
    ajaxUrl = void 0;
    ajaxType = void 0;
    ajaxHash = void 0;
    adapter = Adapter.create({
      ajax: function(url, type, hash) {
        var success, that;

        that = this;
        if (hash.data && type === 'GET') {
          url += "&" + Em.$.param(hash.data);
        }
        success = hash.success;
        ajaxUrl = url;
        ajaxType = type;
        ajaxHash = hash;
        if (success) {
          return hash.success = function(json) {
            return success.call(that, json);
          };
        }
      }
    });
    store = DS.Store.create({
      revision: DS.CURRENT_API_REVISION,
      adapter: adapter
    });
    Person = DS.Model.extend({
      name: DS.attr('string')
    });
    return Person.toString = function() {
      return 'App.Person';
    };
  });
  afterEach(function() {
    adapter.destroy();
    store.destroy();
    person = null;
    return people = null;
  });
  describe('#findMany', function() {
    return it('makes a GET and returns matched items', function(done) {
      people = store.findMany(Person, ['1', '2']);
      expectUrl('/persons');
      expectType('POST');
      ajaxHash.success({
        persons: [
          {
            _id: '1',
            name: 'Yehuda'
          }, {
            _id: '2',
            name: 'TJ'
          }
        ]
      });
      expect(people.get('length'), 2);
      person = people.objectAt(0);
      expect(person.get('id'), '1');
      person = store.find(Person, 1);
      expect(person.get('id'), '1');
      return done();
    });
  });
  return describe('#findQuery', function() {
    return it('makes a POST and returns matched items', function(done) {
      var data, name;

      name = 'Yehuda Katz';
      data = {
        name: name
      };
      people = store.find(Person, data);
      expectStates('loaded', false);
      expectUrl('/persons');
      expectType('POST');
      ajaxHash.success({
        persons: [
          {
            _id: '1',
            name: name
          }
        ]
      });
      expect(people.get('length'), 1);
      person = people.objectAt(0);
      expect(person.get('id'), '1');
      person = store.find(Person, 1);
      expect(person.get('id'), '1');
      return done();
    });
  });
});
