// Generated by CoffeeScript 1.6.2
var express, utils;

express = require('express');

utils = require('./utils');

module.exports = function(modelsArray) {
  var app, items, m, modelsHash, name, plural, _i, _len;

  app = express();
  modelsHash = {};
  for (_i = 0, _len = modelsArray.length; _i < _len; _i++) {
    m = modelsArray[_i];
    modelsHash[m.modelName.toLowerCase()] = utils.makeModelObj(m);
  }
  for (name in modelsHash) {
    m = modelsHash[name];
    utils.setAssociations(modelsHash, name);
  }
  for (name in modelsHash) {
    m = modelsHash[name];
    items = m.items;
    plural = m.pluralName;
    app.get("/" + plural, items.all);
    app.post("/" + plural, items.create);
    app.get("/" + plural + "/:id", items.one);
    app.put("/" + plural + "/:id", items.update);
    app.del("/" + plural + "/:id", items.remove);
  }
  return app;
};
