// Generated by CoffeeScript 1.6.2
var items;

items = require('./items');

exports.makeModelObj = function(model) {
  var obj;

  obj = {};
  obj.Model = model;
  obj.singularName = model.modelName.toLowerCase();
  obj.pluralName = model.collection.name;
  obj.belongsToName = "" + obj.singularName + "_id";
  obj.hasManyName = "" + obj.singularName + "_ids";
  return obj;
};

exports.setAssociations = function(modelsHash, modelName) {
  var belongsToPaths, hasManyPaths, k, modelObj, schema, _i, _len, _ref;

  modelObj = modelsHash[modelName];
  schema = modelObj.Model.schema;
  hasManyPaths = [];
  belongsToPaths = [];
  _ref = Object.keys(schema.paths);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    k = _ref[_i];
    if (k.slice(-3) === '_id') {
      modelName = k.slice(0, k.length - 3);
      if (k !== '_id') {
        belongsToPaths.push(modelsHash[modelName]);
      }
    } else if (k.slice(-4) === '_ids') {
      modelName = k.slice(0, k.length - 4);
      hasManyPaths.push(modelsHash[modelName]);
    }
  }
  modelObj.hasManyPaths = hasManyPaths;
  modelObj.belongsToPaths = belongsToPaths;
  return modelObj.items = items(modelObj);
};
