// Generated by CoffeeScript 1.6.3
var app, express;

express = require('express');

app = module.exports = express();

app.use(express.session({
  cookie: {
    maxAge: 7 * 24 * 60 * 60 * 1000
  },
  key: 'express.sid',
  secret: 'development secret'
}));
