// Generated by CoffeeScript 1.6.3
var app, express;

express = require('express');

app = module.exports = express();

app.use(function(req, res, next) {
  req.isAuthenticated = function() {
    return true;
  };
  req.user = user;
  return next();
});
